// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Quy trình thanh toán', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    const server = process.env.SELENIUM_REMOTE_URL;
    if (server) {
      driver = await new Builder().forBrowser('firefox').usingServer(server).build();
    } else {
      driver = await new Builder().forBrowser('firefox').build();
    }
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Quy trình thanh toán', async function() {
    await driver.get("https://frontend-production-3a24.up.railway.app/")
    await driver.manage().window().setRect({ width: 588, height: 696 })
    try {
      const explore = await driver.wait(until.elementLocated(By.linkText("Explore")), 10000)
      await driver.wait(until.elementIsVisible(explore), 5000)
      await explore.click()
    } catch (e) {
      console.error('Could not find Explore link. Page source:')
      console.error(await driver.getPageSource())
      throw e
    }
    await driver.findElement(By.id("search")).click()
    await driver.findElement(By.id("search")).sendKeys("Bed")
    {
      let dropdown
      try {
        dropdown = await driver.wait(until.elementLocated(By.id("category")), 10000)
        await dropdown.findElement(By.xpath("//option[. = 'Beds']")).click()
      } catch (e) {
        console.error('Could not find #category element. Page source:')
        console.error(await driver.getPageSource())
        throw e
      }
    }
    await driver.findElement(By.css("option:nth-child(4)")).click()
    {
      const dropdown = await driver.findElement(By.id("sorting"))
      await dropdown.findElement(By.xpath("//option[. = 'Price: High to low']")).click()
    }
    await driver.findElement(By.css("#sorting > option:nth-child(2)")).click()
    try {
      // prefer a more flexible selector and wait for at least one product card to appear
      const cards = await driver.wait(until.elementsLocated(By.css('.animate-fadeIn .w-full')), 10000)
      if (cards && cards.length > 0) {
        await driver.wait(until.elementIsVisible(cards[0]), 5000)
        await cards[0].click()
      } else {
        throw new Error('No product cards found')
      }
    } catch (e) {
      console.error('Could not find product card (.animate-fadeIn .w-full). Page source:')
      console.error(await driver.getPageSource())
      throw e
    }
    try {
      const w8 = await driver.wait(until.elementLocated(By.css(".w-8")), 10000)
      await driver.wait(until.elementIsVisible(w8), 5000)
      await w8.click()
    } catch (e) {
      console.error('Could not find .w-8 element. Page source:')
      console.error(await driver.getPageSource())
      throw e
    }
    vars["Sign"] = await driver.findElements(By.xpath("//*[contains(@class, \'py-2\')]/*[contains(@class, \'px-4\')]")).length
    if (!!await driver.executeScript("return (arguments[0] > 0)", vars["Sign"])) {
      await driver.findElement(By.css(".py-2 > .px-4")).click()
    } else {
      await driver.findElement(By.css(".text-left")).click()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("asd@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123123")
    await driver.findElement(By.css(".bg-dark")).click()
    try {
      const explore2 = await driver.wait(until.elementLocated(By.linkText("Explore")), 10000)
      await driver.wait(until.elementIsVisible(explore2), 5000)
      await explore2.click()
    } catch (e) {
      console.error('Could not find Explore link (after login). Page source:')
      console.error(await driver.getPageSource())
      throw e
    }
    await driver.findElement(By.css(".animate-fadeIn:nth-child(2) .text-white")).click()
    await driver.findElement(By.css(".transition-colors:nth-child(2) path")).click()
    await driver.findElement(By.css(".p-3")).sendKeys("Address")
    await driver.findElement(By.css(".mt-4")).click()
    try {
      const cardNumber = await driver.wait(until.elementLocated(By.id("cardNumber")), 15000)
      await driver.wait(until.elementIsVisible(cardNumber), 5000)
      await cardNumber.click()
      await cardNumber.sendKeys("4111 1111 1111 1111")

      const cardExpiry = await driver.wait(until.elementLocated(By.id("cardExpiry")), 10000)
      await driver.wait(until.elementIsVisible(cardExpiry), 5000)
      await cardExpiry.click()
      await cardExpiry.sendKeys("08 / 28")

      const cardCvc = await driver.wait(until.elementLocated(By.id("cardCvc")), 10000)
      await driver.wait(until.elementIsVisible(cardCvc), 5000)
      await cardCvc.click()
      await cardCvc.sendKeys("811")

      const billingName = await driver.wait(until.elementLocated(By.id("billingName")), 10000)
      await driver.wait(until.elementIsVisible(billingName), 5000)
      await billingName.click()
      await billingName.sendKeys("Guest")

      const submit = await driver.wait(until.elementLocated(By.css(".SubmitButton-IconContainer")), 10000)
      await driver.wait(until.elementIsVisible(submit), 5000)
      await submit.click()
    } catch (e) {
      console.error('Could not find payment input(s). Page source:')
      console.error(await driver.getPageSource())
      throw e
    }
  })
})
